[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.7",
    "reportlab>=4.4.1",
    "scikit-learn>=1.6.1",
]
